### ISSUE TITLE
gunicorn 재시작이 안되는 문제 트러블슈팅

### ISSUE THREAD

**Issue by kangroklee** [Youth-is-the-best/Youth-BE#15]
gunicorn이 whewareyou 자체를 못 찾거나 whewareyou/settings.py의 모듈을 찾지 못하면 binding에 실패하여 restart 안됨.

[해결을 위해 한 것 2가지]
- venv를 프로젝트 폴더 안으로 옮김 (gunicorn.service config파일도 같이 수정)
- corsheaders.middleware를 주석처리

**Comment by kangroklee** [comment]
문제는, 이러면 cors가 안되는듯 하다...

**Comment by cherrynniii** [comment]
혹시  'corsheaders.middleware.CorsMiddleware'를 주석 처리한 이유가 뭔가요...?

**Comment by kangroklee** [comment]
넣으면 gunicorn이 restart가 안되더라고요ㅜ

**Comment by cherrynniii** [comment]
아 잠깐만 설마 venv 경로가 바뀌었는데 gunicorn.service를 수정 안 해서 그런가?? 한 번 확인해볼게

**Comment by kangroklee** [comment]
<img width="454" alt="image" src="https://github.com/user-attachments/assets/b766a63c-cb9b-4309-b710-bbdfeee2a63d">
cors미들웨어가 정의된 순서가 중요한것 같네요! 너무 앞은 안되지만 commonmiddleware바로 앞이여야 되는듯합니다

**Comment by cherrynniii** [comment]
그렇군여.. 해결 되어 다행임다
